Script started on 2017年03月13日 (週一) 05時41分05秒
]0;sixigma@sixigma-MS-7592: ~/Documents/Lab1sixigma@sixigma-MS-7592:~/Documents/Lab1$ g++ lab1.cpp
]0;sixigma@sixigma-MS-7592: ~/Documents/Lab1sixigma@sixigma-MS-7592:~/Documents/Lab1$ ./a.out
Please give an input number:22
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;sixigma@sixigma-MS-7592: ~/Documents/Lab1sixigma@sixigma-MS-7592:~/Documents/Lab1$ exit

Script done on 2017年03月13日 (週一) 05時41分26秒
